frr defaults traditional
hostname core2
log stdout informational
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.2/32
!
interface eth1
 description core2-core1
 ip address 10.0.0.1/31
!
interface eth2
 description core2-dub2
 ip address 10.0.11.0/31
!
interface eth3
 description core2-lon2
 ip address 10.0.21.0/31
!
router bgp 65000
 bgp router-id 10.255.0.2
 no bgp ebgp-requires-policy
 neighbor 10.0.0.0 remote-as 65000
 neighbor 10.0.11.1 remote-as 65100
 neighbor 10.0.21.1 remote-as 65200
 !
 address-family ipv4 unicast
  neighbor 10.0.0.0 activate
  neighbor 10.0.0.0 next-hop-self
  neighbor 10.0.11.1 activate
  neighbor 10.0.21.1 activate
 exit-address-family
!
line vty
!
