frr defaults traditional
hostname lon2
log stdout informational
service integrated-vtysh-config
!
interface lo
 ip address 10.200.0.2/32
 ip address 10.210.0.2/32
 ip ospf area 0.0.0.0
!
interface eth1
 description lon2-core2
 ip address 10.0.21.1/31
!
interface eth2
 description lon2-lon1
 ip address 10.2.0.1/31
 ip ospf network point-to-point
 ip ospf area 0.0.0.0
!
router ospf
 ospf router-id 10.200.0.2
 passive-interface lo
!
router bgp 65200
 bgp router-id 10.200.0.2
 no bgp ebgp-requires-policy
 neighbor 10.0.21.0 remote-as 65000
 neighbor 10.200.0.1 remote-as 65200
 neighbor 10.200.0.1 update-source lo
 !
 address-family ipv4 unicast
  network 10.210.0.2/32
  neighbor 10.0.21.0 activate
  neighbor 10.200.0.1 activate
  neighbor 10.200.0.1 next-hop-self
 exit-address-family
!
line vty
!
