frr defaults traditional
hostname core1
log stdout informational
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.1/32
!
interface eth1
 description core1-core2
 ip address 10.0.0.0/31
!
interface eth2
 description core1-dub1
 ip address 10.0.10.0/31
!
interface eth3
 description core1-lon1
 ip address 10.0.20.0/31
!
router bgp 65000
 bgp router-id 10.255.0.1
 no bgp ebgp-requires-policy
 neighbor 10.0.0.1 remote-as 65000
 neighbor 10.0.10.1 remote-as 65100
 neighbor 10.0.20.1 remote-as 65200
 !
 address-family ipv4 unicast
  neighbor 10.0.0.1 activate
  neighbor 10.0.0.1 next-hop-self
  neighbor 10.0.10.1 activate
  neighbor 10.0.20.1 activate
 exit-address-family
!
line vty
!
